name: smart_campus_access
description: "A Flutter app for smart campus access with role-based login and virtual ID generation."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  google_ml_kit: ^0.19.0
  image_picker: ^1.1.2
  image: ^4.1.3
  google_mlkit_face_detection: ^0.12.0
  google_mlkit_commons: ^0.9.0
  path_provider: ^2.1.1
  mongo_dart: ^0.9.3
  qr_code_scanner_plus: ^2.0.10+1
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - assets/def-avatar.jpg